[project]
name = "weather"
version = "0.1.0"
description = "MCP Servers for Weather and Pokemon"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.18.0",
]
